#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/*********************************global variables***********************************************/
    const char firstPrompt[] = "Please choose an option:\n1) Register an account\n2) Login\n\
3) Search for books\n4) Display all books\n5) Quit\n Option:";

    const char librarianPrompt[] = "Please choose an option:\n1) Add a book\n2) Remove a book\n\
3) Search for a book\n4) Display all books\n5)Log out\n Option:";

    const char searchMenu[] = "Please choose an option:\n1) Find books by title\n2) Find books \
by author\n3) Find books by year\n4) Return to previous menu\n Option:";

    const char invalidOption[] = "Sorry, the option you entered was invalid, please try again.\n\n";

    const char userPrompt[] = "Please enter an option:\n1) Borrow a book\n2) Return a book\n\
3) Search for book\n4) Display all books\n5) Log out\n Option: ";

    const char noSuchBook[] = "Sorry, no such book.\n";

    char answer[10];
    char answer2[10];
    char *answerPtr = answer;
    char *answerPtr2 = answer2;
/**********************************global variables*********************************/

typedef struct _Book {
    unsigned int id; //Book ID
    char *title; //book title
    char *authors; //comma separated list of authors
    unsigned int year; // year of publication
    unsigned int copies; //number of copies the library has
    struct _Book *next;
}Book;

typedef struct _BookArray {
	Book* array; // pointer to array (or linked list) of struct Book.
	unsigned int length; // number of elements in the (Book*) array 
}BookArray;

typedef struct _BorrowBook{
    unsigned int id;
    char *title;
    char *authors;
    unsigned int year;
    struct _BorrowBook* next;
}BorrowBook;

// declare a struct to store user
typedef struct _User {
    char *username;
    char *password;
    // books that the user borrow
    BorrowBook *borrowBook;
    struct _User*next;
}User;

// a head pointer that points to the head node of the book
Book *headPtrBook;

// a head pointer that points to the head node of the user
User *headPtrUser;

// a head pointer that points to the head node of the user
BorrowBook *headPtrBorrowBook;

// declare a libaray administrator
User librarian;

/******************************************functions**********************************************/
// function to make string a zero string
void nullifyString(char *string){
    for(; *string != '\0'; *string++){
        *string = '\0';
    }
    *string = '\0';
}

// function to find book by id
Book* findBookByID (unsigned int id){
    // declare a book pointer to traverse the linked list for books
    Book *bookPtr = headPtrBook->next;
    while(bookPtr != NULL){
        if(bookPtr->id == id){
            break;
        }
        bookPtr = bookPtr->next;
    }
    return bookPtr;
}

// function to borrow books for user
void borrowBook(Book *book, User user){
    BorrowBook* borrowBookPtr = user.borrowBook;
    // find the end of the borrowed book
    while(borrowBookPtr->next != NULL){
        borrowBookPtr = borrowBookPtr->next;
    }
    // new borrowBook
    BorrowBook* newBorrowBook = (BorrowBook*)malloc(sizeof(BorrowBook));
    newBorrowBook->id = book->id;
    newBorrowBook->authors = book->authors;
    newBorrowBook->title = book->title;
    newBorrowBook->year = book->year;
    newBorrowBook->next = NULL;

    // assign the new borrowBook
    borrowBookPtr->next = newBorrowBook;
}

// function to check if the user borrow two same book
int checkSameBorrowBook(unsigned int id, User user){
    int i = 0;
    BorrowBook* borrowBookPtr = user.borrowBook->next;
    while(borrowBookPtr != NULL){
        if(borrowBookPtr->id == id){
            i = 1;
            break;
        }
        borrowBookPtr = borrowBookPtr->next;
    }
    return i;
}

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(const char* filename){
    FILE *file;
    file = fopen(filename, "w");
    Book* bookPtr = headPtrBook->next;
    char title[50];
    char authors[50];

    if(!file){
        return -1;
    }

    while(bookPtr){
        strcpy(title,bookPtr->title);
        strcpy(authors,bookPtr->authors);
        // output the data of the node to the file books.txt
        fprintf(file,"%u\n%s\n%s\n%u\n%u\n\n",bookPtr->id, title, authors,\
        bookPtr->year, bookPtr->copies);
        memset(title,'\0',sizeof(title));
        memset(authors,'\0',sizeof(authors));
        bookPtr = bookPtr->next;
    }
    fclose(file);

    return 0;
}


//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(const char* filename){
    headPtrBook = (Book*)malloc(sizeof(Book*));
    Book* bookPtr;
    Book* newBook;
    bookPtr = headPtrBook;
    FILE *file;
    file = fopen(filename, "r");
    if (!file) {
        return -1;
	}
    char str[50];
    while(!feof(file)){
        newBook = (Book*)malloc(sizeof(Book));
        
        fscanf(file,"%u",&newBook->id);
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        newBook->title = (char*)malloc(sizeof(str));
        strcpy(newBook->title,str);
        memset(str,'\0',strlen(str));
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        newBook->authors = (char*)malloc(sizeof(str));
        strcpy(newBook->authors,str);
        memset(str,'\0',strlen(str));
        fgetc(file);

        fscanf(file,"%u",&newBook->year);
        fgetc(file);

        fscanf(file,"%u",&newBook->copies);
        fgetc(file);
        bookPtr->next = newBook;
        bookPtr = newBook;
    }
    bookPtr->next = NULL;
    fclose(file);

    return 0;
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(char bookTitle[], char bookAuthors[], unsigned int bookCopies, unsigned int bookYear){
    if(bookCopies <= 0){
        return -1;
    }else{
    Book* newBook = (Book*)malloc(sizeof(Book));
    newBook->title = (char*)malloc(50);
    strcpy(newBook->title, bookTitle);
    newBook->authors = (char*)malloc(50);
    strcpy(newBook->authors, bookAuthors);
    newBook->copies = bookCopies;
    newBook->year = bookYear;
    newBook->next = NULL;

    Book* bookPtr = headPtrBook->next;
    while(bookPtr->next != NULL){
        bookPtr = bookPtr->next;
    }
    newBook->id = (bookPtr->id)+1;
    bookPtr->next = newBook;

    return 0;
    }

}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(char title[], char authors[], unsigned int copies, unsigned int year){
    Book* bookPtr = headPtrBook;
    while(bookPtr->next != NULL){
        if(!strcmp (bookPtr->next->title,title) && !strcmp(bookPtr->next->authors,authors) && \
        bookPtr->next->copies == copies && bookPtr->next->year == year){
            break;
        }
        bookPtr = bookPtr->next;
    }    
    // book can not be removed
    if(bookPtr == NULL){
        return 0;
    // book can be removed
    }else{
        bookPtr->next = bookPtr->next->next;
        bookPtr = bookPtr->next;
        while(bookPtr != NULL){
            bookPtr->id--;
            bookPtr = bookPtr->next;
        }
        return 1;
    }
}

//finds books with a given title.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_title (const char *title){
    // declare a BookArray
    BookArray titleArray;
    // initialize the book array
    titleArray.array = headPtrBook;
    titleArray.length = 0;

    Book* arrayPtr = titleArray.array;

    Book* bookPtr = headPtrBook->next;
    while(bookPtr != NULL){
        if(!strcmp(bookPtr->title,title)){
            Book* newArray = (Book*)malloc(sizeof(Book));
            newArray->id = bookPtr->id;
            newArray->title = bookPtr->title;
            newArray->authors = bookPtr->authors;
            newArray->year = bookPtr->year;
            newArray->copies = bookPtr->copies;
            newArray->next = NULL;

            // assign the newArray
            titleArray.length ++;
            arrayPtr->next = newArray;
            arrayPtr = arrayPtr->next;
            
        }
        bookPtr = bookPtr->next;
    }
    arrayPtr->next = NULL;
    return titleArray;
}

//finds books with the given authors.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_author (const char *author){
    // declare a BookArray
    BookArray authorArray;
    // initialize the book array
    authorArray.array = headPtrBook;
    authorArray.length = 0;

    Book* arrayPtr = authorArray.array;

    Book* bookPtr = headPtrBook->next;
    while(bookPtr != NULL){
        if(!strcmp(bookPtr->authors,author)){
            Book* newArray = (Book*)malloc(sizeof(Book));
            newArray->id = bookPtr->id;
            newArray->title = bookPtr->title;
            newArray->authors = bookPtr->authors;
            newArray->year = bookPtr->year;
            newArray->copies = bookPtr->copies;
            newArray->next = NULL;

            // assign the newArray
            authorArray.length ++;
            arrayPtr->next = newArray;
            arrayPtr = arrayPtr->next;
            
        }
        bookPtr = bookPtr->next;
    }
    arrayPtr->next = NULL;
    return authorArray;
}

//finds books published in the given year.
//returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
//provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
//array is the null pointer.
BookArray find_book_by_year (unsigned int year){
        // declare a BookArray
    BookArray yearArray;
    // initialize the book array
    yearArray.array = headPtrBook;
    yearArray.length = 0;

    Book* arrayPtr = yearArray.array;

    Book* bookPtr = headPtrBook->next;
    while(bookPtr != NULL){
        if(bookPtr->year == year){
            Book* newArray = (Book*)malloc(sizeof(Book));
            newArray->id = bookPtr->id;
            newArray->title = bookPtr->title;
            newArray->authors = bookPtr->authors;
            newArray->year = bookPtr->year;
            newArray->copies = bookPtr->copies;
            newArray->next = NULL;

            // assign the newArray
            yearArray.length ++;
            arrayPtr->next = newArray;
            arrayPtr = arrayPtr->next;
            
        }
        bookPtr = bookPtr->next;
    }
    arrayPtr->next = NULL;
    return yearArray;
}

// function to display the book array
void displayBookArray(BookArray bookArray){
    // declare a book pointer to traverse the linked list for books
    Book *bookPtr = bookArray.array->next;
    printf("ID    Title                                                 Authors\
                                            year  copies\n");
    while(bookPtr != NULL){
        printf("%-2d    %-50s    %-50s ",bookPtr->id, bookPtr->title, bookPtr->authors);
        printf("%-4d  %-2d\n", bookPtr->year, bookPtr->copies);
        bookPtr = bookPtr->next;
    }
}

// function to display all books
void displayBooks(){
    Book* bookPtr = headPtrBook->next;
    printf("ID    Title                                                 Authors\
                                            year  copies\n");
    
    while(bookPtr != NULL){
        printf("%-2d    %-50s    %-50s ",bookPtr->id, bookPtr->title, bookPtr->authors);
        printf("%-4d  %-2d\n", bookPtr->year, bookPtr->copies);
        bookPtr = bookPtr->next;
    }
}

// function to display all borrow books
void displayBorrowBooks(User user){
    printf("ID    Title                                                 Authors\
                                               year\n");
    BorrowBook* borrowBookPtr = user.borrowBook->next;
    while(borrowBookPtr != NULL){
        printf("%-2u    %-50s    %-50s    ",borrowBookPtr->id, borrowBookPtr->title, borrowBookPtr->authors);
        printf("%-4u\n", borrowBookPtr->year);
        borrowBookPtr = borrowBookPtr->next;
    }
}

// function to check the returned book
BorrowBook* checkReturnBook(unsigned int id, User user){
    BorrowBook* borrowBookPtr = user.borrowBook->next;
    while(borrowBookPtr != NULL){
        if(borrowBookPtr->id == id){
            break;
        }
        borrowBookPtr = borrowBookPtr->next;
    }
    return borrowBookPtr;
}

// function to return the book
void returnBook(BorrowBook* returnBook, User user){
    BorrowBook* borrowBookPtr = user.borrowBook->next;
    while(borrowBookPtr->next != returnBook){
        borrowBookPtr = borrowBookPtr->next;
    }
    borrowBookPtr->next = returnBook->next;
    returnBook->next = NULL;
}

// function to check if the user name already exists
int checkUsername(char *name){
    // declare a user pointer to traverse the linked list for the user
    User *usrPtr = headPtrUser->next;
    int i = 0;
    while(usrPtr != NULL){
        if(!strcmp(usrPtr->username,name)){
            i = 1;
            break;
        }
        usrPtr = usrPtr->next;
    }

    return i;
}

// function to store username
void storeUsername(char username[], char password[]){
    // declare a user pointer to traverse the linked list for the username
    User* usrPtr = headPtrUser;
    while(usrPtr->next != NULL){
        usrPtr = usrPtr->next;
    }
    // declare a user pointer to store the new user and allocate the memory
    User *newUser = (User *)malloc(sizeof(User*));
    char str[30];

    strcpy(str,username);
    newUser->username = (char*)malloc(sizeof(str));
    strcpy(newUser->username,str);
    memset(str,'\0',30);

    strcpy(str,password);
    newUser->password = (char*)malloc(sizeof(str));
    strcpy(newUser->password,str);
    memset(str,'\0',30);

    newUser->borrowBook = (BorrowBook*)malloc(sizeof(BorrowBook));
    newUser->borrowBook->next = NULL;
    // newUser->borrow = NULL;
    newUser->next = NULL;
    usrPtr->next = newUser;
}

// function to store user in file
int storeUserInFile(const char* filename){
    FILE *file;
    file = fopen(filename,"w");
    if(!file){
        return -1;
    }
    User* userPtr = headPtrUser->next;
    char str[30];
    BorrowBook* borrowBookPtr;
    while(userPtr){
        strcpy(str,userPtr->username);
        fprintf(file,"%s\n",str);
        memset(str,'\0',30);
        
        strcpy(str,userPtr->password);
        fprintf(file,"%s\n\n",str);
        memset(str,'\0',30);

        borrowBookPtr = userPtr->borrowBook->next;
        while(borrowBookPtr){
            fprintf(file,"%u\n",borrowBookPtr->id);
            strcpy(str,borrowBookPtr->title);
            fprintf(file,"%s\n",str);
            memset(str,'\0',30);
            strcpy(str,borrowBookPtr->authors);
            fprintf(file,"%s\n",borrowBookPtr->authors);
            memset(str,'\0',30);
            fprintf(file,"%u\n\n",borrowBookPtr->year);

            borrowBookPtr = borrowBookPtr->next;
        }
        fprintf(file,"**********");
        userPtr = userPtr->next;
    }
    fclose(file);
    return 0;
}

int loadUser(const char* filename){
    FILE *file;
    file = fopen(filename,"r");
    if(!file){
        return -1;
    }
    BorrowBook* borrowBookPtr = headPtrBorrowBook;
    BorrowBook* newBorrowBook;
    User* userPtr;
    User* newUser;
    userPtr = headPtrUser;
    char str[30];
    while(!feof(file)){
        newUser = (User*)malloc(sizeof(User));
        newUser->borrowBook = headPtrBorrowBook;

        fscanf(file,"%[^\n]s",str);
        newUser->username = (char*)malloc(sizeof(str));
        strcpy(newUser->username,str);
        memset(str,'\0',strlen(str));
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        newUser->password = (char*)malloc(sizeof(str));
        strcpy(newUser->password,str);
        memset(str,'\0',strlen(str));
        fgetc(file);
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        while(strcmp(str,"**********")){
        newBorrowBook = (BorrowBook*)malloc(sizeof(BorrowBook));
        fscanf(file,"%u",&newBorrowBook->id);
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        newBorrowBook->title = (char*)malloc(sizeof(str));
        strcpy(newBorrowBook->title,str);
        memset(str,'\0',strlen(str));
        fgetc(file);

        fscanf(file,"%[^\n]s",str);
        newBorrowBook->authors = (char*)malloc(sizeof(str));
        strcpy(newBorrowBook->authors,str);
        memset(str,'\0',strlen(str));
        fgetc(file);

        fscanf(file,"%u",&newBorrowBook->year);
        borrowBookPtr->next = newBorrowBook;
        borrowBookPtr = newBorrowBook;
        fscanf(file,"%[^\n]s",str);
        }

        fgetc(file);
        memset(str,'\0',strlen(str));
        newUser->next = NULL;
        userPtr->next = newUser;
        userPtr = newUser;
    }
    fclose(file);
    return 0;
}

// function to check password
User* checkPassword(char *username, char *password){
    // declare a user pointer to traverse the linked list for user
    User *userPtr = headPtrUser->next;
    while(userPtr != NULL){
        if(!strcmp(userPtr->username,username)){
            if(!strcmp(userPtr->password,password)){
                break;
            }
        }
        userPtr = userPtr->next;
    }

    return userPtr;
}

// function to 
// function to search for a book
void searchForBook(){
    while (1){
        printf("Loading search menu...\n\n");
        printf("%s",searchMenu);
        gets(answer);
        // wrong option
        if(*answer <'1' || *answer > '4'){
            printf("%s", invalidOption);
            // find books by title
        }else if(*answer == '1'){
            nullifyString(answerPtr);
            printf("Please enter the title: ");
            gets(answer);
            // find the book
            if(find_book_by_title(answer).array->next != NULL){
                displayBookArray(find_book_by_title(answer));
                // can not find the book
            }else{
                printf("%s", noSuchBook);
            }
            // find books by author
        }else if(*answer == '2'){
            nullifyString(answerPtr);
            printf("Please enter the author: ");
            gets(answer);
            // find the book
            if(find_book_by_author(answer).array->next != NULL){
                displayBookArray(find_book_by_author(answer));
                // can not find the book
            }else{
                printf("%s", noSuchBook);
            }
            // find books by year
        }else if(*answer == '3'){
            printf("Please enter the year: ");
            gets(answer);
            if(find_book_by_year(atoi(answer)).array->next != NULL){
                displayBookArray(find_book_by_year(atoi(answer)));
            }else{
                printf("%s", noSuchBook);
            }
            // return to previous menu
        }else if(*answer == '4'){
            break;
        }
    }
}

int main(void){
    // declaration of users
    headPtrUser = (User*)malloc(sizeof(User));
    headPtrUser->next = &librarian;

    // declaration of borrow book
    headPtrBorrowBook = (BorrowBook*)malloc(sizeof(BorrowBook));
    headPtrBorrowBook->next = NULL;
    // declaration of library administrator (librarian)
    librarian.username = "librarian";
    librarian.password = "librarian";
    librarian.borrowBook = headPtrBorrowBook;
    librarian.borrowBook->next = NULL;
    librarian.next = NULL;

    load_books("books.txt");
    store_books("store.txt");
    storeUserInFile("users.txt");
    loadUser("users.txt");

    while(1){
        printf("%s",firstPrompt);
        gets(answer);

        // wrong option
        if(*answer < '1' || *answer > '5'){
            nullifyString(answerPtr);
            printf("%s",invalidOption);
            
            continue;
            // register an account
        }else if(*answer == '1'){
            while(1){
                printf("Please enter a username: ");
                gets(answer);
                if(checkUsername(answer)){
                    printf("Sorry, registration unsuccessful, the username you entered already exists.\n");
                    continue;
                }else{
                    break;
                }
            }
            printf("Please enter a password: ");
            gets(answer2);
            storeUsername(answer, answer2);
            nullifyString(answerPtr);
            nullifyString(answerPtr2);
            // login
        }else if(*answer == '2'){
            while(1){
                printf("Please enter your username: ");
                gets(answer);
                if(checkUsername(answer)){
                    printf("Please enter your password: ");
                    gets(answer2);
                    if(checkPassword(answer,answer2)){
                        // library administrator account
                        if(!strcmp(answer,"librarian")){
                            nullifyString(answerPtr);
                            nullifyString(answerPtr2);
                            while(1){
                                printf("(logged in as: librarian)\n");
                                printf("%s",librarianPrompt);
                                gets(answer);
                                // wrong option
                                if(*answer<'1' || *answer>'5'){
                                    printf("%s",invalidOption);
                                    nullifyString(answerPtr);
                                    continue;
                                    // add a book
                                }else if(*answer == '1'){
                                    nullifyString(answerPtr);
                                    char title[50], authors[50];
                                    nullifyString(title);
                                    nullifyString(authors);
                                    unsigned int copies, year;
                                    printf("Enter the title of the book you wish to add: ");
                                    gets(title);
                                    printf("Enter the author of the book you wish to add: ");
                                    gets(authors);
                                    printf("Enter the year of that the book you wish to add: ");
                                    scanf("%d", &year);
                                    printf("Enter the number of book that you wish to add: ");
                                    scanf("%d",&copies);
                                    getchar();
                                    if(!add_book(title, authors,copies,year)){
                                        printf("Books are added successfully!\n");
                                    }else{
                                        printf("Failed to add books.\n");
                                    }
                                    // remove a book
                                }else if(*answer == '2'){
                                    nullifyString(answerPtr);
                                    char title[50], authors[50];
                                    nullifyString(title);
                                    nullifyString(authors);
                                    unsigned int copies, year;
                                    printf("Enter the title of the book you wish to remove: ");
                                    gets(title);
                                    printf("Enter the author of the book you wish to remove: ");
                                    gets(authors);
                                    printf("Enter the year of that the book you wish to remove: ");
                                    scanf("%u", &year);
                                    printf("Enter the number of book that you wish to remove: ");
                                    scanf("%u",&copies);
                                    nullifyString(answerPtr);
                                    getchar();
                                    if(remove_book(title, authors, copies, year)){
                                        printf("Book was successfully removed!\n");
                                    }else{
                                        printf("Failed to remove book\n");
                                    }
                                    //search for a book
                                }else if(*answer == '3'){
                                    nullifyString(answerPtr);
                                    searchForBook();
                                    // display all books
                                }else if(*answer == '4'){
                                    displayBooks();
                                    // log out
                                }else if(*answer == '5'){
                                    break;
                                }
                            }
                            // user account
                        }else{
                            User currentUser = *checkPassword(answer,answer2);
                            while(1){
                                printf("(logged in as: %s)\n",answer);
                                printf("%s", userPrompt);
                                nullifyString(answerPtr);
                                gets(answer);
                                // wrong option
                                if(*answer < '1' || *answer > '5'){
                                    nullifyString(answerPtr);
                                    printf("%s", invalidOption);
                                    // borrow a book
                                }else if(*answer == '1'){
                                    nullifyString(answerPtr);
                                    printf("Enter the ID number of the book you wish to borrow: ");
                                    gets(answer);
                                    // the book can be borrowed the book exists in the library 
                                    // and not borrowed by the same user
                                    if(findBookByID(atoi(answer)) != NULL &&\
                                    findBookByID(atoi(answer))->copies >= 0 && !checkSameBorrowBook\
                                    (atoi(answer),currentUser)){
                                        borrowBook(findBookByID(atoi(answer)),currentUser);
                                        printf("You have successfully borrowed the book!\n");
                                        // the book is already borrowed
                                    }else if(checkSameBorrowBook(atoi(answer),currentUser)){
                                        printf\
                                        ("Sorry, you already have a copy of this book on loan.\n");
                                        // the book can not be borrowd
                                    }else{
                                        printf("Sorry, book is borrowed unsuccessfully.\n");
                                    }
                                    // return a book
                                }else if(*answer == '2'){
                                    nullifyString(answerPtr);
                                    printf("Below is the list of Books you are currently borrowing:\n");
                                    displayBorrowBooks(currentUser);
                                    printf("Enter the ID number of the book you wish to return: ");
                                    gets(answer);
                                    // the book can be returned: the book was borrowed before
                                    if(checkReturnBook(atoi(answer),currentUser) != NULL){
                                        returnBook(checkReturnBook(atoi(answer),currentUser),\
                                        currentUser);
                                        printf("Returned book successfully!.\n");
                                    }else{
                                        printf("Cannot return book!\n");
                                    }
                                    // search for a book
                                }else if(*answer == '3'){
                                    nullifyString(answerPtr);
                                    searchForBook();
                                }else if(*answer == '4'){
                                    displayBooks();
                                }else if (*answer == '5'){
                                    printf("Logging out...\n");
                                    break;
                                }
                            }
                        }
                    }
                }else{
                    printf("Sorry, the username does not exist.\n");
                    continue;
                }
            }
            // search for a book
        }else if(*answer == '3'){
            searchForBook();
        }else if(*answer == '4'){
            displayBooks();
        }else if(*answer == '5'){
            printf("Thank you for using the library!\n");
            return 0;
        }
    }
    

}